apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fallow_v1alpha1_reclaimpolicy.yaml
  - fallow_v1alpha1_reclaimpolicy_notify_only.yaml
  - fallow_v1alpha1_reclaimpolicy_ephemeral.yaml
